// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfGfiLpsIY0Bl3b7YuH2IMvOBoez5IGNI',
    appId: '1:196085635144:web:f13010c2acc95c4e32a07d',
    messagingSenderId: '196085635144',
    projectId: 'docnow-83995',
    authDomain: 'docnow-83995.firebaseapp.com',
    storageBucket: 'docnow-83995.firebasestorage.app',
    measurementId: 'G-8328M9HHYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39BHYafAWl6Ace_M3J9vglKxvyDNrfuc',
    appId: '1:196085635144:android:b31bc536b19f662332a07d',
    messagingSenderId: '196085635144',
    projectId: 'docnow-83995',
    storageBucket: 'docnow-83995.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfGfiLpsIY0Bl3b7YuH2IMvOBoez5IGNI',
    appId: '1:196085635144:web:d20bcc89bfe2767432a07d',
    messagingSenderId: '196085635144',
    projectId: 'docnow-83995',
    authDomain: 'docnow-83995.firebaseapp.com',
    storageBucket: 'docnow-83995.firebasestorage.app',
    measurementId: 'G-JXRY75ZYS2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xjBy51drY0yoK79fQZ_XfLzpdT72ZZE',
    appId: '1:196085635144:ios:7e2d84c0e286509f32a07d',
    messagingSenderId: '196085635144',
    projectId: 'docnow-83995',
    storageBucket: 'docnow-83995.firebasestorage.app',
    iosBundleId: 'com.example.firebaseetasks',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xjBy51drY0yoK79fQZ_XfLzpdT72ZZE',
    appId: '1:196085635144:ios:7e2d84c0e286509f32a07d',
    messagingSenderId: '196085635144',
    projectId: 'docnow-83995',
    storageBucket: 'docnow-83995.firebasestorage.app',
    iosBundleId: 'com.example.firebaseetasks',
  );

}